### CREAR LA BASE DE DATOS VENTASHN
CREATE DATABASE ventashn;
USE ventashn;

CREATE TABLE DEPARTMENT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR(17) NOT NULL
);

CREATE TABLE USERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(20) NOT NULL,
    LAST_NAME VARCHAR(20) NOT NULL,
    PROFILE_PIC INT NOT NULL,
    USER_EMAIL VARCHAR(50) NOT NULL,
    USER_PASSWORD VARCHAR(50) NOT NULL,
    IS_COMPANY BOOLEAN NOT NULL,
    IS_ADMIN BOOLEAN DEFAULT FALSE,
    SCORE INT DEFAULT 0,
    DEPARTMENT_ID INT NOT NULL,
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID)
);

#EN STATE IRIA ALGO COMO N:NUEVO , U:USADO, R:REACONDICIONADO, D:DAÑADO, NA:NO APLICABLE
CREATE TABLE PRODUCTS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(100) NOT NULL,
    PRODUCT_DESCRIPTION VARCHAR(500) NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL,
    STATE VARCHAR(1) NOT NULL,
    IS_SELLING BOOLEAN NOT NULL,
    DATE_ADDED DATE NOT NULL,
    DEPARTMENT_ID INT NOT NULL,
    USER_SELLER_ID INT NOT NULL,
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID),
    FOREIGN KEY (USER_SELLER_ID) REFERENCES USERS(ID)
);

CREATE TABLE IMAGES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    IMAGE_TYPE VARCHAR(10) NOT NULL,
    IMAGE_NAME VARCHAR(100) NOT NULL,
    IMAGE_DATA MEDIUMBLOB NOT NULL,
    PRODUCT_ID INT NOT NULL,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID)
);

CREATE TABLE CATEGORIES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CATEGORIE_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE PRODUCTS_CATEGORIES (
    PRODUCT_ID INT NOT NULL,
    CATEGORIE_ID INT NOT NULL,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID),
    FOREIGN KEY (CATEGORIE_ID) REFERENCES CATEGORIES(ID)
);


# ORDER_PRIOR SERIA P:PRECIO, V:VENDEDOR, A:ANTIGUEDAD
# PREFEREDDY SERIA L:LUNES, M:MARTES, X:MIERCOLES, J:JUEVES, V:VIERNES, S:SÁBADO, D:DOMINGO

CREATE TABLE SUSCRIPTIONS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    DEPARTMENT_ID INT NOT NULL,
    ORDER_PRIOR VARCHAR(1) NOT NULL,
    MIN_SELLER_SCORE INT,
    PREFERRED_DAY VARCHAR(1) NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID)
);

CREATE TABLE SUSCRIPTIONS_CATEGORIES (
	SUSCRIPTION_ID INT NOT NULL,
    CATEGORIE_ID INT NOT NULL,
    FOREIGN KEY (SUSCRIPTION_ID) REFERENCES SUSCRIPTIONS(ID),
    FOREIGN KEY (CATEGORIE_ID) REFERENCES CATEGORIES(ID)
);

CREATE TABLE REASONS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    REASON_NAME VARCHAR(50) NOT NULL,
    REASON_DESCRIPTION VARCHAR(500) NOT NULL
);

CREATE TABLE COMPLAINTS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    REASON_ID INT NOT NULL,
    COMPLAINT_DESCRIPTION VARCHAR(500) NOT NULL,
    CREATOR_USER_ID INT NOT NULL,
    REPORTED_USER_ID INT NOT NULL,
    ADMIN_USER_ID INT NOT NULL,
    FOREIGN KEY (REASON_ID) REFERENCES REASONS(ID),
    FOREIGN KEY (CREATOR_USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (REPORTED_USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (ADMIN_USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE REVIEWS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    REVIEW_VALUE INT NOT NULL,
    REVIEWED_USER_ID INT NOT NULL,
    REVIEWER_USER_ID INT NOT NULL,
    REVIEW_DATE DATE NOT NULL,
    FOREIGN KEY (REVIEWED_USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (REVIEWER_USER_ID) REFERENCES USERS(ID)
);
