use ventashn;

delete from users where id = 1 ;

delete from users where id =2;

delete from users where id = 3 ;

delete from users where id = 4;

delete from users where id = 5 ;

delete from users where id =6 ;

delete from users where id = 7 ;

delete from users where id = 8 ;

delete from users where id = 9 ;

delete from users where id = 12;

INSERT INTO DEPARTMENTS (DEPARTMENT_NAME) VALUES ("Atlántida");
INSERT INTO DEPARTMENTS (DEPARTMENT_NAME) VALUES ("Colón");
INSERT INTO DEPARTMENTS (DEPARTMENT_NAME) VALUES ("Comayagua");
INSERT INTO DEPARTMENTS (DEPARTMENT_NAME) VALUES ("Copán");
INSERT INTO DEPARTMENTS (DEPARTMENT_NAME) VALUES ("Cortés");
INSERT INTO DEPARTMENTS (DEPARTMENT_NAME) VALUES ("Choluteca");
INSERT INTO DEPARTMENTS (DEPARTMENT_NAME) VALUES ("El Paraíso");
INSERT INTO DEPARTMENTS (DEPARTMENT_NAME) VALUES ("Francisco Morazán");
INSERT INTO DEPARTMENTS (DEPARTMENT_NAME) VALUES ("Gracias a Dios");
INSERT INTO DEPARTMENTS (DEPARTMENT_NAME) VALUES ("Intibucá");
INSERT INTO DEPARTMENTS (DEPARTMENT_NAME) VALUES ("Islas de la Bahía");
INSERT INTO DEPARTMENTS (DEPARTMENT_NAME) VALUES ("La Paz");
INSERT INTO DEPARTMENTS (DEPARTMENT_NAME) VALUES ("Lempira");
INSERT INTO DEPARTMENTS (DEPARTMENT_NAME) VALUES ("Ocotepeque");
INSERT INTO DEPARTMENTS (DEPARTMENT_NAME) VALUES ("Olancho");
INSERT INTO DEPARTMENTS (DEPARTMENT_NAME) VALUES ("Santa Bárbara");
INSERT INTO DEPARTMENTS (DEPARTMENT_NAME) VALUES ("Valle");
INSERT INTO DEPARTMENTS (DEPARTMENT_NAME) VALUES ("Yoro");



INSERT INTO DEPARTMENTS (CATEGORIE_NAME) VALUES ("Hogar");
INSERT INTO DEPARTMENTS (CATEGORIE_NAME) VALUES ("Automotriz");
INSERT INTO DEPARTMENTS (CATEGORIE_NAME) VALUES ("Electrónica");
INSERT INTO DEPARTMENTS (CATEGORIE_NAME) VALUES ("Muebles");
INSERT INTO DEPARTMENTS (CATEGORIE_NAME) VALUES ("Ropa");
INSERT INTO DEPARTMENTS (CATEGORIE_NAME) VALUES ("Juguetes");
INSERT INTO DEPARTMENTS (CATEGORIE_NAME) VALUES ("Libros");
INSERT INTO DEPARTMENTS (CATEGORIE_NAME) VALUES ("Instrumentos");
INSERT INTO DEPARTMENTS (CATEGORIE_NAME) VALUES ("Deportes");


